//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoresWebApp.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Items = new HashSet<Order_Items>();
        }
    
        public long Order_Id { get; set; }
        public Nullable<long> Customer_Id { get; set; }
        public long Order_StatusId { get; set; }
        public System.DateTime Order_Date { get; set; }
        public System.DateTime Required_Date { get; set; }
        public Nullable<System.DateTime> Shipped_Date { get; set; }
        public long Store_Id { get; set; }
        public long Staff_Id { get; set; }
        public Nullable<System.DateTime> CreatedTs { get; set; }
        public Nullable<System.DateTime> LastModifiedTs { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Items> Order_Items { get; set; }
        public virtual Order_Status Order_Status { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Store Store { get; set; }
    }
}
