//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoresWebApp.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        public Nullable<long> Order_Id { get; set; }
        public long Item_Id { get; set; }
        public long Product_Id { get; set; }
        public int Quantity { get; set; }
        public decimal List_Price { get; set; }
        public decimal Discount { get; set; }
        public Nullable<System.DateTime> CreatedTs { get; set; }
        public Nullable<System.DateTime> LastModifiedTs { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
    }
}
