//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoresWebApp.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public long Id { get; set; }
        public Nullable<long> Store_Id { get; set; }
        public Nullable<long> Product_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreatedTs { get; set; }
        public Nullable<System.DateTime> LastModifiedTs { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
